@startuml singleton

title Singleton Design Pattern in C++

class Singleton { 
  - Singleton()
  + Singleton(Singleton const&) = delete;
  + operator=(Singleton const&) = delete;
  + {static} getInstance(): Singleton& 
}

@enduml