name: Sync to Gist
on:
  push:
    branches:
      - 'main'
jobs:
  sync-cpp-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gist Repo Sync
        uses: pentatonicfunk/action-gist-repo-sync@v1.8
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: 37725ab7b444fb15c6a917b07495aac6
          source_path: ./design-patterns
  sync-creational-puml-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gist Repo Sync
        uses: pentatonicfunk/action-gist-repo-sync@v1.8
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: 37725ab7b444fb15c6a917b07495aac6
          source_path: ./doc/Creational
  sync-structural-puml-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gist Repo Sync
        uses: pentatonicfunk/action-gist-repo-sync@v1.8
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: 37725ab7b444fb15c6a917b07495aac6
          source_path: ./doc/Structural
  sync-behavioural-puml-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gist Repo Sync
        uses: pentatonicfunk/action-gist-repo-sync@v1.8
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: 37725ab7b444fb15c6a917b07495aac6
          source_path: ./doc/Bevahioural
  sync-singleton-puml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Copy file
        run: |
             mkdir tmp
             cp ./doc/Creational/singleton.puml ./tmp/.
      - name: Gist Repo Sync
        uses: pentatonicfunk/action-gist-repo-sync@v1.8
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: acea0c4240040edd33da0aff986cbd34
          source_path: .tmp

